package helper

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/fprl/ship/internal/caddy"
	"github.com/fprl/ship/internal/config"
	"github.com/fprl/ship/internal/identity"
	"github.com/fprl/ship/internal/store"
	"github.com/fprl/ship/internal/utils"
	"golang.org/x/crypto/bcrypt"
)

func caddyfilePath(app, env string) string {
	return identity.CaddyFragmentFile(app, env)
}

func renderAppCaddyfileWithProcessNames(app, env string, ctx *config.AppContext, release string, processNames map[string]string) (string, error) {
	type hostKey struct {
		host string
		tls  string
	}
	grouped := map[hostKey][]string{}
	for _, name := range sortedKeys(ctx.Routes) {
		route := ctx.Routes[name]
		key := hostKey{host: route.Host, tls: normalizeTLS(route.TLS)}
		grouped[key] = append(grouped[key], name)
	}

	keys := make([]hostKey, 0, len(grouped))
	for key := range grouped {
		keys = append(keys, key)
	}
	sort.Slice(keys, func(i, j int) bool {
		if keys[i].host != keys[j].host {
			return keys[i].host < keys[j].host
		}
		return keys[i].tls < keys[j].tls
	})

	var blocks []string
	for _, key := range keys {
		routeNames := grouped[key]
		sort.SliceStable(routeNames, func(i, j int) bool {
			left := ctx.Routes[routeNames[i]].Path
			right := ctx.Routes[routeNames[j]].Path
			if left == right {
				return routeNames[i] < routeNames[j]
			}
			if left == "" {
				return false
			}
			if right == "" {
				return true
			}
			return len(left) > len(right)
		})

		var prelude string
		if key.tls == "internal" {
			prelude = "\ttls internal\n"
		}
		protection, err := renderPreviewProtection(env, ctx)
		if err != nil {
			return "", err
		}
		var body strings.Builder
		useHandles := len(routeNames) > 1 || ctx.Routes[routeNames[0]].Path != ""
		for _, routeName := range routeNames {
			rendered, err := renderRouteBody(app, env, ctx, routeName, release, processNames, useHandles)
			if err != nil {
				return "", err
			}
			body.WriteString(rendered)
		}
		quotedHost, err := caddy.CaddyQuote(key.host)
		if err != nil {
			return "", err
		}
		blocks = append(blocks, fmt.Sprintf("%s {\n%s%s%s}\n", quotedHost, prelude, protection, body.String()))
	}
	return "# generated by ship server app apply — do not edit\n" + strings.Join(blocks, "\n"), nil
}

// renderPreviewProtection is intentionally gated by the env name first:
// production fragments can never acquire basic_auth from a manifest flag.
func renderPreviewProtection(env string, ctx *config.AppContext) (string, error) {
	if env == productionEnvName || !ctx.PreviewProtected {
		return "", nil
	}
	if ctx.PreviewPassword == "" || ctx.PreviewBypassToken == "" {
		return "", fmt.Errorf("protected preview credentials are missing")
	}
	hash, err := bcrypt.GenerateFromPassword([]byte(ctx.PreviewPassword), bcrypt.DefaultCost)
	if err != nil {
		return "", fmt.Errorf("hash preview password: %w", err)
	}
	quotedToken, err := caddy.CaddyQuote(ctx.PreviewBypassToken)
	if err != nil {
		return "", err
	}
	quotedHash, err := caddy.CaddyQuote(string(hash))
	if err != nil {
		return "", err
	}
	share := ""
	shareAuthCondition := ""
	if ctx.PreviewShareToken != "" {
		// Caddy's one-line query matcher takes a single param=val token.
		quotedShareQuery, err := caddy.CaddyQuote("ship_share=" + ctx.PreviewShareToken)
		if err != nil {
			return "", err
		}
		quotedShareCookie, err := caddy.CaddyQuote("*ship_share=" + ctx.PreviewShareToken + "*")
		if err != nil {
			return "", err
		}
		quotedSetCookie, err := caddy.CaddyQuote("ship_share=" + ctx.PreviewShareToken + "; Path=/; HttpOnly; Secure")
		if err != nil {
			return "", err
		}
		share = fmt.Sprintf("\t@ship_share query %s\n\thandle @ship_share {\n\t\theader Set-Cookie %s\n\t\tredir {path} temporary\n\t}\n", quotedShareQuery, quotedSetCookie)
		shareAuthCondition = fmt.Sprintf("\t\tnot header Cookie %s\n\t\tnot query %s\n", quotedShareCookie, quotedShareQuery)
	}
	// The basic_auth matcher is negated, so a request carrying the exact
	// bypass header or share cookie skips auth entirely.
	return fmt.Sprintf("%s\t@ship_auth {\n\t\tnot header x-ship-bypass %s\n%s\t}\n\tbasic_auth @ship_auth {\n\t\tteam %s\n\t}\n", share, quotedToken, shareAuthCondition, quotedHash), nil
}

func renderRouteBody(app, env string, ctx *config.AppContext, routeName string, release string, processNames map[string]string, wrap bool) (string, error) {
	route := ctx.Routes[routeName]
	body, err := renderRouteDirectives(app, env, ctx, routeName, release, processNames)
	if err != nil {
		return "", err
	}
	if !wrap {
		return indent(body, 1), nil
	}
	if route.Path == "" {
		return "\thandle {\n" + indent(body, 2) + "\t}\n", nil
	}
	if route.Serve != "" {
		return fmt.Sprintf("\thandle %s {\n\t\trewrite * /\n%s\t}\n\thandle_path %s/* {\n%s\t}\n",
			route.Path, indent(body, 2), route.Path, indent(body, 2)), nil
	}
	return fmt.Sprintf("\thandle %s {\n%s\t}\n\thandle %s/* {\n%s\t}\n",
		route.Path, indent(body, 2), route.Path, indent(body, 2)), nil
}

func renderRouteDirectives(app, env string, ctx *config.AppContext, routeName string, release string, processNames map[string]string) (string, error) {
	route := ctx.Routes[routeName]
	switch {
	case route.Process != "":
		proc, ok := ctx.Processes[route.Process]
		if !ok || proc.Port == nil {
			return "", fmt.Errorf("route %q references process %q with no port", routeName, route.Process)
		}
		upstream := identity.ContainerName(app, env, route.Process, release)
		if processNames != nil && processNames[route.Process] != "" {
			upstream = processNames[route.Process]
		}
		return fmt.Sprintf("reverse_proxy http://%s:%d\n", upstream, *proc.Port), nil
	case route.Serve != "":
		root := filepath.Join(identity.StaticDir(app, env), "releases", release, config.RouteStorageName(routeName))
		quotedRoot, err := caddy.CaddyQuote(root)
		if err != nil {
			return "", fmt.Errorf("route %q: %v", routeName, err)
		}
		return fmt.Sprintf("root * %s\nfile_server\n", quotedRoot), nil
	case route.Redirect != "":
		quotedTo, err := caddy.CaddyQuote("https://" + route.Redirect + "{uri}")
		if err != nil {
			return "", fmt.Errorf("route %q: %v", routeName, err)
		}
		return fmt.Sprintf("redir %s permanent\n", quotedTo), nil
	default:
		return "", fmt.Errorf("route %q has no target", routeName)
	}
}

func normalizeTLS(tls string) string {
	if tls == "" {
		return "auto"
	}
	return tls
}

func indent(s string, levels int) string {
	prefix := strings.Repeat("\t", levels)
	lines := strings.Split(s, "\n")
	for i, line := range lines {
		if line == "" {
			continue
		}
		lines[i] = prefix + line
	}
	return strings.Join(lines, "\n")
}

func writeAppCaddyfile(app, env string, ctx *config.AppContext, release string) error {
	return writeAppCaddyfileWithProcessNames(app, env, ctx, release, nil)
}

func writeAppCaddyfileWithProcessNames(app, env string, ctx *config.AppContext, release string, processNames map[string]string) error {
	content, err := renderAppCaddyfileWithProcessNames(app, env, ctx, release, processNames)
	if err != nil {
		return err
	}
	path := caddyfilePath(app, env)
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return err
	}
	return store.AtomicWrite(path, []byte(content), caddyFragmentMode([]byte(content)))
}

// caddyFragmentMode keeps fragments carrying the preview-protection bypass
// token root-only (they are a capability); plain fragments stay 0644 so
// the deploy user can read them (existing behavior the smoke relies on).
func caddyFragmentMode(content []byte) os.FileMode {
	if bytes.Contains(content, []byte("x-ship-bypass")) {
		return 0600
	}
	return 0644
}

// snapshotCaddyFragment reads the existing fragment so a failed deploy
// can restore it. Returns (contents, true, nil) when a fragment exists,
// (nil, false, nil) when nothing is there, or an error for anything
// other than ENOENT.
func snapshotCaddyFragment(path string) ([]byte, bool, error) {
	data, err := os.ReadFile(path)
	if err == nil {
		return data, true, nil
	}
	if os.IsNotExist(err) {
		return nil, false, nil
	}
	return nil, false, err
}

// restoreCaddyFragment puts back what snapshotCaddyFragment captured.
// If there was no previous fragment, remove the new one so subsequent
// reloads don't trip on it.
func restoreCaddyFragment(path string, prev []byte, existed bool) error {
	if existed {
		// Atomic like the normal write path: a concurrent full-config
		// parse must never observe a half-restored fragment.
		return store.AtomicWrite(path, prev, caddyFragmentMode(prev))
	}
	if err := os.Remove(path); err != nil && !os.IsNotExist(err) {
		return err
	}
	return nil
}

type caddyReloadStageError struct {
	Stage      string
	Err        error
	RestoreErr error
}

func (e caddyReloadStageError) Error() string {
	if e.RestoreErr != nil {
		return fmt.Sprintf("caddy %s failed AND restore failed (manual fix required): %v (restore: %v)", e.Stage, e.Err, e.RestoreErr)
	}
	return fmt.Sprintf("caddy %s failed: %v", e.Stage, e.Err)
}

func (e caddyReloadStageError) Unwrap() error {
	return e.Err
}

// reloadCaddyOrRestore serializes on a box-wide lock: validate and
// reload parse the FULL Caddyfile, so two concurrent reloads could
// otherwise apply a config parsed before another actor's fragment
// write — resurrecting a revoked share link or a reaped preview's
// route. Fragment writes are atomic renames, every writer reloads
// after writing, and reloads are serial: the last reload always
// carries the newest state of every fragment.
func reloadCaddyOrRestore(caddyPath string, prevFragment []byte, prevExisted bool) error {
	reloadLock, err := acquireLockFile(filepath.Join(appEnvLockDir(), "caddy-reload.lock"))
	if err != nil {
		return err
	}
	defer func() { _ = reloadLock.Release() }()
	if _, err := utils.RunChecked("podman", []string{"exec", "caddy", "caddy", "validate", "--config", "/etc/caddy/Caddyfile", "--adapter", "caddyfile"}, ""); err != nil {
		if restoreErr := restoreCaddyFragment(caddyPath, prevFragment, prevExisted); restoreErr != nil {
			return caddyReloadStageError{Stage: "validate", Err: err, RestoreErr: restoreErr}
		}
		return caddyReloadStageError{Stage: "validate", Err: err}
	}
	if _, err := utils.RunChecked("podman", []string{"exec", "caddy", "caddy", "reload", "--config", "/etc/caddy/Caddyfile"}, ""); err != nil {
		restoreErr := restoreCaddyFragment(caddyPath, prevFragment, prevExisted)
		return caddyReloadStageError{Stage: "reload", Err: err, RestoreErr: restoreErr}
	}
	return nil
}
