package helper

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/fprl/ship/internal/caddy"
	"github.com/fprl/ship/internal/config"
	"github.com/fprl/ship/internal/identity"
	"github.com/fprl/ship/internal/store"
	"github.com/fprl/ship/internal/utils"
)

func caddyfilePath(app, env string) string {
	return identity.CaddyFragmentFile(app, env)
}

func renderAppCaddyfileWithProcessNames(app, env string, ctx *config.AppContext, release string, processNames map[string]string) (string, error) {
	type hostKey struct {
		host string
		tls  string
	}
	grouped := map[hostKey][]string{}
	for _, name := range sortedKeys(ctx.Routes) {
		route := ctx.Routes[name]
		key := hostKey{host: route.Host, tls: normalizeTLS(route.TLS)}
		grouped[key] = append(grouped[key], name)
	}

	keys := make([]hostKey, 0, len(grouped))
	for key := range grouped {
		keys = append(keys, key)
	}
	sort.Slice(keys, func(i, j int) bool {
		if keys[i].host != keys[j].host {
			return keys[i].host < keys[j].host
		}
		return keys[i].tls < keys[j].tls
	})

	var blocks []string
	for _, key := range keys {
		routeNames := grouped[key]
		sort.SliceStable(routeNames, func(i, j int) bool {
			left := ctx.Routes[routeNames[i]].Path
			right := ctx.Routes[routeNames[j]].Path
			if left == right {
				return routeNames[i] < routeNames[j]
			}
			if left == "" {
				return false
			}
			if right == "" {
				return true
			}
			return len(left) > len(right)
		})

		var prelude string
		if key.tls == "internal" {
			prelude = "\ttls internal\n"
		}
		protection, err := renderPreviewProtection(env, ctx)
		if err != nil {
			return "", err
		}
		var body strings.Builder
		useHandles := len(routeNames) > 1 || ctx.Routes[routeNames[0]].Path != ""
		for _, routeName := range routeNames {
			rendered, err := renderRouteBody(app, env, ctx, routeName, release, processNames, useHandles)
			if err != nil {
				return "", err
			}
			body.WriteString(rendered)
		}
		quotedHost, err := caddy.CaddyQuote(key.host)
		if err != nil {
			return "", err
		}
		blocks = append(blocks, fmt.Sprintf("%s {\n%s%s%s}\n", quotedHost, prelude, protection, body.String()))
	}
	return "# generated by ship server app apply — do not edit\n" + strings.Join(blocks, "\n"), nil
}

// renderPreviewProtection is gated by the env name first: production fragments
// can never acquire preview capability auth.
func renderPreviewProtection(env string, ctx *config.AppContext) (string, error) {
	if env == productionEnvName {
		return "", nil
	}
	if ctx.PreviewCapabilityToken == "" {
		return "", fmt.Errorf("preview capability is missing")
	}
	token := ctx.PreviewCapabilityToken
	query, err := caddy.CaddyQuote("ship=" + token)
	if err != nil {
		return "", err
	}
	cookie, err := caddy.CaddyQuote("*ship=" + token + "*")
	if err != nil {
		return "", err
	}
	header, err := caddy.CaddyQuote(token)
	if err != nil {
		return "", err
	}
	strip, err := caddy.CaddyQuote("(^)ship=" + token + "(?:;[ \\t]*|$)|(;[ \\t]*)ship=" + token + ";[ \\t]*|;[ \\t]*ship=" + token + "$")
	if err != nil {
		return "", err
	}
	replacement, err := caddy.CaddyQuote("$1$2")
	if err != nil {
		return "", err
	}
	setCookie, err := caddy.CaddyQuote("ship=" + token + "; Path=/; HttpOnly; Secure")
	if err != nil {
		return "", err
	}
	// The route block forces source order. At Caddy's default directive
	// order request_header runs before respond, so the credential strips
	// would erase the header/cookie before the 401 matcher reads them and
	// every request would be denied (verified against real Caddy).
	return fmt.Sprintf("\troute {\n\t\t@ship_capability_query query %s\n\t\thandle @ship_capability_query {\n\t\t\theader Set-Cookie %s\n\t\t\tredir {path} temporary\n\t\t}\n\t\t@ship_capability_denied {\n\t\t\tnot header x-ship-capability %s\n\t\t\tnot header Cookie %s\n\t\t}\n\t\trespond @ship_capability_denied 401\n\t\trequest_header -x-ship-capability\n\t\trequest_header Cookie %s %s\n\t}\n", query, setCookie, header, cookie, strip, replacement), nil
}

func renderRouteBody(app, env string, ctx *config.AppContext, routeName string, release string, processNames map[string]string, wrap bool) (string, error) {
	route := ctx.Routes[routeName]
	body, err := renderRouteDirectives(app, env, ctx, routeName, release, processNames)
	if err != nil {
		return "", err
	}
	if !wrap {
		return indent(body, 1), nil
	}
	if route.Path == "" {
		return "\thandle {\n" + indent(body, 2) + "\t}\n", nil
	}
	if route.Serve != "" {
		return fmt.Sprintf("\thandle %s {\n\t\trewrite * /\n%s\t}\n\thandle_path %s/* {\n%s\t}\n",
			route.Path, indent(body, 2), route.Path, indent(body, 2)), nil
	}
	return fmt.Sprintf("\thandle %s {\n%s\t}\n\thandle %s/* {\n%s\t}\n",
		route.Path, indent(body, 2), route.Path, indent(body, 2)), nil
}

func renderRouteDirectives(app, env string, ctx *config.AppContext, routeName string, release string, processNames map[string]string) (string, error) {
	route := ctx.Routes[routeName]
	switch {
	case route.Process != "":
		proc, ok := ctx.Processes[route.Process]
		if !ok || proc.Port == nil {
			return "", fmt.Errorf("route %q references process %q with no port", routeName, route.Process)
		}
		upstream := identity.ContainerName(app, env, route.Process, release)
		if processNames != nil && processNames[route.Process] != "" {
			upstream = processNames[route.Process]
		}
		return fmt.Sprintf("reverse_proxy http://%s:%d\n", upstream, *proc.Port), nil
	case route.Serve != "":
		root := filepath.Join(identity.StaticDir(app, env), "releases", release, config.RouteStorageName(routeName))
		quotedRoot, err := caddy.CaddyQuote(root)
		if err != nil {
			return "", fmt.Errorf("route %q: %v", routeName, err)
		}
		return fmt.Sprintf("root * %s\nfile_server\n", quotedRoot), nil
	case route.Redirect != "":
		quotedTo, err := caddy.CaddyQuote("https://" + route.Redirect + "{uri}")
		if err != nil {
			return "", fmt.Errorf("route %q: %v", routeName, err)
		}
		return fmt.Sprintf("redir %s permanent\n", quotedTo), nil
	default:
		return "", fmt.Errorf("route %q has no target", routeName)
	}
}

func normalizeTLS(tls string) string {
	if tls == "" {
		return "auto"
	}
	return tls
}

func indent(s string, levels int) string {
	prefix := strings.Repeat("\t", levels)
	lines := strings.Split(s, "\n")
	for i, line := range lines {
		if line == "" {
			continue
		}
		lines[i] = prefix + line
	}
	return strings.Join(lines, "\n")
}

// renderAndReloadAppCaddy validates a scratch copy of the complete Caddy
// configuration before replacing the serving fragment. The serving tree is
// untouched during validation, so a crash cannot leave a staging *.caddy file
// for a later reload to import.
func renderAndReloadAppCaddy(path, app, env string, ctx *config.AppContext, release string, processNames map[string]string) error {
	reloadLock, err := acquireLockFile(filepath.Join(appEnvLockDir(), "caddy-reload.lock"))
	if err != nil {
		return err
	}
	defer func() { _ = reloadLock.Release() }()

	previous, existed, err := snapshotCaddyFragment(path)
	if err != nil {
		return err
	}
	content, err := renderAppCaddyfileWithProcessNames(app, env, ctx, release, processNames)
	if err != nil {
		return err
	}
	validationDir, err := prepareCaddyValidationTree(path, content)
	if err != nil {
		return err
	}
	defer func() { _ = os.RemoveAll(validationDir) }()
	validationConfig := filepath.Join(validationDir, "Caddyfile")
	if _, err := utils.RunChecked("podman", []string{"exec", "caddy", "caddy", "validate", "--config", validationConfig, "--adapter", "caddyfile"}, ""); err != nil {
		return caddyReloadStageError{Stage: "validate", Err: err}
	}
	// This is the first mutation of the serving fragment. AtomicWrite keeps
	// the old inode in place until the validated replacement is ready.
	if err := store.AtomicWrite(path, []byte(content), caddyFragmentMode([]byte(content))); err != nil {
		return err
	}
	if _, err := utils.RunChecked("podman", []string{"exec", "caddy", "caddy", "reload", "--config", "/etc/caddy/Caddyfile"}, ""); err != nil {
		restoreErr := restoreCaddyFragment(path, previous, existed)
		return caddyReloadStageError{Stage: "reload", Err: err, RestoreErr: restoreErr}
	}
	return nil
}

// prepareCaddyValidationTree builds a private config tree under /etc/caddy
// (or the corresponding test root). The real serving conf.d directory is
// copied into it and the replacement is written there, so validation sees
// the exact assembled config without exposing any temporary *.caddy file to
// the serving import glob.
func prepareCaddyValidationTree(path, replacement string) (string, error) {
	configRoot := filepath.Dir(filepath.Dir(path))
	validationDir, err := os.MkdirTemp(configRoot, ".ship-caddy-validate-*")
	if err != nil {
		return "", err
	}
	cleanup := func(err error) (string, error) {
		_ = os.RemoveAll(validationDir)
		return "", err
	}
	validationConfDir := filepath.Join(validationDir, "conf.d")
	if err := os.MkdirAll(validationConfDir, 0755); err != nil {
		return cleanup(err)
	}
	mainConfig, err := os.ReadFile("/etc/caddy/Caddyfile")
	if err != nil {
		if !os.IsNotExist(err) {
			return cleanup(fmt.Errorf("read Caddyfile for validation: %v", err))
		}
		mainConfig = []byte("import conf.d/*.caddy\n")
	}
	if err := store.AtomicWrite(filepath.Join(validationDir, "Caddyfile"), mainConfig, 0644); err != nil {
		return cleanup(err)
	}
	entries, err := os.ReadDir(filepath.Dir(path))
	if err != nil {
		return cleanup(err)
	}
	found := false
	for _, entry := range entries {
		if entry.IsDir() || filepath.Ext(entry.Name()) != ".caddy" {
			continue
		}
		data, err := os.ReadFile(filepath.Join(filepath.Dir(path), entry.Name()))
		if err != nil {
			return cleanup(err)
		}
		if entry.Name() == filepath.Base(path) {
			data = []byte(replacement)
			found = true
		}
		if err := store.AtomicWrite(filepath.Join(validationConfDir, entry.Name()), data, caddyFragmentMode(data)); err != nil {
			return cleanup(err)
		}
	}
	if !found {
		if err := store.AtomicWrite(filepath.Join(validationConfDir, filepath.Base(path)), []byte(replacement), caddyFragmentMode([]byte(replacement))); err != nil {
			return cleanup(err)
		}
	}
	return validationDir, nil
}

// caddyFragmentMode keeps fragments carrying a preview capability
// token root-only (they are a capability); plain fragments stay 0644 so
// the deploy user can read them (existing behavior the smoke relies on).
func caddyFragmentMode(content []byte) os.FileMode {
	if bytes.Contains(content, []byte("x-ship-capability")) {
		return 0600
	}
	return 0644
}

// snapshotCaddyFragment reads the existing fragment so a failed deploy
// can restore it. Returns (contents, true, nil) when a fragment exists,
// (nil, false, nil) when nothing is there, or an error for anything
// other than ENOENT.
func snapshotCaddyFragment(path string) ([]byte, bool, error) {
	data, err := os.ReadFile(path)
	if err == nil {
		return data, true, nil
	}
	if os.IsNotExist(err) {
		return nil, false, nil
	}
	return nil, false, err
}

// restoreCaddyFragment puts back what snapshotCaddyFragment captured.
// If there was no previous fragment, remove the new one so subsequent
// reloads don't trip on it.
func restoreCaddyFragment(path string, prev []byte, existed bool) error {
	if existed {
		// Atomic like the normal write path: a concurrent full-config
		// parse must never observe a half-restored fragment.
		return store.AtomicWrite(path, prev, caddyFragmentMode(prev))
	}
	if err := os.Remove(path); err != nil && !os.IsNotExist(err) {
		return err
	}
	return nil
}

type caddyReloadStageError struct {
	Stage      string
	Err        error
	RestoreErr error
}

func (e caddyReloadStageError) Error() string {
	if e.RestoreErr != nil {
		return fmt.Sprintf("caddy %s failed AND restore failed (manual fix required): %v (restore: %v)", e.Stage, e.Err, e.RestoreErr)
	}
	return fmt.Sprintf("caddy %s failed: %v", e.Stage, e.Err)
}

func (e caddyReloadStageError) Unwrap() error {
	return e.Err
}

// caddyStageActionError renders a caddyReloadStageError for the user:
// which caddy stage failed during which action, and — when the fragment
// restore ALSO failed — the manual-fix warning with the fragment path.
func caddyStageActionError(err error, action string, caddyPath string) error {
	if err == nil {
		return nil
	}
	var caddyErr caddyReloadStageError
	if !errors.As(err, &caddyErr) {
		return err
	}
	if caddyErr.RestoreErr != nil {
		return fmt.Errorf("caddy %s (%s) failed AND fragment restore failed (manual fix required at %s): %v (restore: %v)", caddyErr.Stage, action, caddyPath, caddyErr.Err, caddyErr.RestoreErr)
	}
	return fmt.Errorf("caddy %s (%s) failed, restored previous fragment: %v", caddyErr.Stage, action, caddyErr.Err)
}

// reloadCaddyOrRestore serializes on a box-wide lock: validate and
// reload parse the FULL Caddyfile, so two concurrent reloads could
// otherwise apply a config parsed before another actor's fragment
// write — resurrecting a revoked share link or a reaped preview's
// route. Fragment writes are atomic renames, every writer reloads
// after writing, and reloads are serial: the last reload always
// carries the newest state of every fragment.
func reloadCaddyOrRestore(caddyPath string, prevFragment []byte, prevExisted bool) error {
	reloadLock, err := acquireLockFile(filepath.Join(appEnvLockDir(), "caddy-reload.lock"))
	if err != nil {
		return err
	}
	defer func() { _ = reloadLock.Release() }()
	if _, err := utils.RunChecked("podman", []string{"exec", "caddy", "caddy", "validate", "--config", "/etc/caddy/Caddyfile", "--adapter", "caddyfile"}, ""); err != nil {
		if restoreErr := restoreCaddyFragment(caddyPath, prevFragment, prevExisted); restoreErr != nil {
			return caddyReloadStageError{Stage: "validate", Err: err, RestoreErr: restoreErr}
		}
		return caddyReloadStageError{Stage: "validate", Err: err}
	}
	if _, err := utils.RunChecked("podman", []string{"exec", "caddy", "caddy", "reload", "--config", "/etc/caddy/Caddyfile"}, ""); err != nil {
		restoreErr := restoreCaddyFragment(caddyPath, prevFragment, prevExisted)
		return caddyReloadStageError{Stage: "reload", Err: err, RestoreErr: restoreErr}
	}
	return nil
}
